version: '3.4'

services:
  local-warhouse-api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/WarehouseApplication/Api/Dockerfile
    environment:
      OWNER: "Secretochka"

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Secretochka2442"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserv/data:/var/opt/mssql/data
      - ./sqlserv/log:/var/opt/mssql/log
      - ./sqlserv/secrets:/var/opt/mssql/secrets


  migrationapplay:
    image: ${DOCKER_REGISTRY-}migrationapplay
    build:
      context: .
      dockerfile: MigrationApplay/Dockerfile
    depends_on:
      - sql-server-db




